[workspace]
members = [
    "crates/*",
    "sim",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
# local crates
event = { path = "crates/event" }
graphics = { path = "crates/graphics" }
marcher = { path = "crates/marcher" }
shader-bindings = { path = "crates/shader-bindings" }

# shared dependencies
bytemuck = { version = "1.14", features = [ "derive" ] }
memoffset = "0.9.0"

# graphics
wgpu = { version = "0.19" }
winit = { version = "0.29" }

# build deps
wgsl_to_wgpu = { version = "0.5" }
regex = "1.10"

# error handling
thiserror = "1.0"
anyhow = "1.0"