[package]
name = "software-renderer"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
wcpu = { path = "../wcpu" }

glam = { workspace = true }
image = { workspace = true }