[package]
name = "sim"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
event = { workspace = true }
graphics = { workspace = true }
marcher = { workspace = true }
gui = { workspace = true }

winit = { workspace = true }
anyhow = { workspace = true }

[build-dependencies]
shader-bindings = { workspace = true }