[package]
name = "wgsl-bindgen"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror = { workspace = true }
wgsl_to_wgpu = "0.6"
regex = "1.10"
naga = "0.19"